// swift-tools-version: 6.2
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import PackageDescription

let package = Package(
  name: "GoogleCloudGSuiteAddOnsV1",
  platforms: [.macOS(.v15)],
  products: [
    .library(name: "GoogleCloudGSuiteAddOnsV1", targets: ["GoogleCloudGSuiteAddOnsV1"])
  ],
  dependencies: [
    .package(path: "../../generated/google-apps-script-type"),
    .package(path: "../../generated/google-apps-script-type-calendar"),
    .package(path: "../../generated/google-apps-script-type-docs"),
    .package(path: "../../generated/google-apps-script-type-drive"),
    .package(path: "../../generated/google-apps-script-type-gmail"),
    .package(path: "../../generated/google-apps-script-type-sheets"),
    .package(path: "../../generated/google-apps-script-type-slides"),
    .package(path: "../../packages/auth"),
    .package(path: "../../packages/gax"),
    .package(path: "../../packages/wkt"),
    .package(url: "https://github.com/apple/swift-log", from: "1.12.0"),
  ],
  targets: [
    .target(
      name: "GoogleCloudGSuiteAddOnsV1",
      dependencies: [
        .product(name: "GoogleAppsScriptType", package: "google-apps-script-type"),
        .product(name: "GoogleAppsScriptTypeCalendar", package: "google-apps-script-type-calendar"),
        .product(name: "GoogleAppsScriptTypeDocs", package: "google-apps-script-type-docs"),
        .product(name: "GoogleAppsScriptTypeDrive", package: "google-apps-script-type-drive"),
        .product(name: "GoogleAppsScriptTypeGmail", package: "google-apps-script-type-gmail"),
        .product(name: "GoogleAppsScriptTypeSheets", package: "google-apps-script-type-sheets"),
        .product(name: "GoogleAppsScriptTypeSlides", package: "google-apps-script-type-slides"),
        .product(name: "GoogleCloudAuth", package: "auth"),
        .product(name: "GoogleCloudGax", package: "gax"),
        .product(name: "GoogleCloudWkt", package: "wkt"),
        .product(name: "Logging", package: "swift-log"),
      ],
    )
  ]
)
