// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The authorization information used when invoking deployment endpoints.
public struct Authorization: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The canonical full name of this resource.
  /// Example:  `projects/123/authorization`
  public var name: Swift.String = Swift.String()

  /// The email address of the service account used to authenticate requests to
  /// add-on callback endpoints.
  public var serviceAccountEmail: Swift.String = Swift.String()

  /// The OAuth client ID used to obtain OAuth access tokens for a user on the
  /// add-on's behalf.
  public var oauthClientId: Swift.String = Swift.String()

  /// Initialize a new instance of `Authorization`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Authorization().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gsuiteaddons.v1.Authorization"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
