// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Google Workspace add-on deployment
public struct Deployment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The deployment resource name.
  /// Example:  projects/123/deployments/my_deployment.
  public var name: Swift.String = Swift.String()

  /// The list of Google OAuth scopes for which to request consent from the end
  /// user before executing an add-on endpoint.
  public var oauthScopes: [Swift.String] = []

  /// The Google Workspace add-on configuration.
  public var addOns: AddOns? = nil

  /// This value is computed by the server based on the version of the
  /// deployment in storage, and may be sent on update and delete requests to
  /// ensure the client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `Deployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Deployment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gsuiteaddons.v1.Deployment"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
