// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class GSuiteAddOnsRetry: GSuiteAddOnsStub {
    let inner: any GSuiteAddOnsStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any GSuiteAddOnsStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func getAuthorization(
      request: GetAuthorizationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Authorization {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAuthorizationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGSuiteAddOnsV1.Authorization
          in
          return try await self.inner.getAuthorization(request: r, options: o)
        })
    }

    public func createDeployment(
      request: CreateDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGSuiteAddOnsV1.Deployment
          in
          return try await self.inner.createDeployment(request: r, options: o)
        })
    }

    public func replaceDeployment(
      request: ReplaceDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ReplaceDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGSuiteAddOnsV1.Deployment
          in
          return try await self.inner.replaceDeployment(request: r, options: o)
        })
    }

    public func getDeployment(
      request: GetDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGSuiteAddOnsV1.Deployment
          in
          return try await self.inner.getDeployment(request: r, options: o)
        })
    }

    public func listDeployments(
      request: ListDeploymentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.ListDeploymentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDeploymentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGSuiteAddOnsV1.ListDeploymentsResponse
          in
          return try await self.inner.listDeployments(request: r, options: o)
        })
    }

    public func deleteDeployment(
      request: DeleteDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteDeployment(request: r, options: o)
        })
    }

    public func installDeployment(
      request: InstallDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: InstallDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.installDeployment(request: r, options: o)
        })
    }

    public func uninstallDeployment(
      request: UninstallDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UninstallDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.uninstallDeployment(request: r, options: o)
        })
    }

    public func getInstallStatus(
      request: GetInstallStatusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.InstallStatus {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetInstallStatusRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGSuiteAddOnsV1.InstallStatus
          in
          return try await self.inner.getInstallStatus(request: r, options: o)
        })
    }
  }
}
