// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class GSuiteAddOnsLogging: GSuiteAddOnsStub {
    let inner: any GSuiteAddOnsStub
    let logger: Logger

    public init(_ inner: any GSuiteAddOnsStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-gsuiteaddons-v1"
      logger[metadataKey: "gcp.client.service"] = "gsuiteaddons"
      logger[metadataKey: "gcp.experimental.swift.client"] = "GSuiteAddOns"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func getAuthorization(
      request: GetAuthorizationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Authorization {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAuthorization",
        action: {
          (r: GetAuthorizationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGSuiteAddOnsV1.Authorization
          in
          return try await self.inner.getAuthorization(request: r, options: o)
        })
    }

    public func createDeployment(
      request: CreateDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDeployment",
        action: {
          (r: CreateDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGSuiteAddOnsV1.Deployment
          in
          return try await self.inner.createDeployment(request: r, options: o)
        })
    }

    public func replaceDeployment(
      request: ReplaceDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "replaceDeployment",
        action: {
          (r: ReplaceDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGSuiteAddOnsV1.Deployment
          in
          return try await self.inner.replaceDeployment(request: r, options: o)
        })
    }

    public func getDeployment(
      request: GetDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDeployment",
        action: {
          (r: GetDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGSuiteAddOnsV1.Deployment
          in
          return try await self.inner.getDeployment(request: r, options: o)
        })
    }

    public func listDeployments(
      request: ListDeploymentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.ListDeploymentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDeployments",
        action: {
          (r: ListDeploymentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGSuiteAddOnsV1.ListDeploymentsResponse
          in
          return try await self.inner.listDeployments(request: r, options: o)
        })
    }

    public func deleteDeployment(
      request: DeleteDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDeployment",
        action: {
          (r: DeleteDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteDeployment(request: r, options: o)
        })
    }

    public func installDeployment(
      request: InstallDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "installDeployment",
        action: {
          (r: InstallDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.installDeployment(request: r, options: o)
        })
    }

    public func uninstallDeployment(
      request: UninstallDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "uninstallDeployment",
        action: {
          (r: UninstallDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.uninstallDeployment(request: r, options: o)
        })
    }

    public func getInstallStatus(
      request: GetInstallStatusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.InstallStatus {
      try await self._intercept(
        request: request,
        options: options,
        name: "getInstallStatus",
        action: {
          (r: GetInstallStatusRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudGSuiteAddOnsV1.InstallStatus
          in
          return try await self.inner.getInstallStatus(request: r, options: o)
        })
    }
  }
}
