// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol GSuiteAddOnsStub {
    func getAuthorization(
      request: GetAuthorizationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Authorization

    func createDeployment(
      request: CreateDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment

    func replaceDeployment(
      request: ReplaceDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment

    func getDeployment(
      request: GetDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.Deployment

    func listDeployments(
      request: ListDeploymentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.ListDeploymentsResponse

    func deleteDeployment(
      request: DeleteDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func installDeployment(
      request: InstallDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func uninstallDeployment(
      request: UninstallDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getInstallStatus(
      request: GetInstallStatusRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudGSuiteAddOnsV1.InstallStatus
  }
}
